### ISSUE TITLE
Fail Cases

### ISSUE THREAD

**Issue by weiffert** [weiffert/Missile-Command#3]
Whenever the program fails with loading a document or can't find a property, entity, or state, the program either continues running, or breaks on the spot. We need to implement something like try, catch or those throw errors things so that if a file isn't there that should be, the program will stop and tell it to the user.

**Comment by coverp** [comment]
In `stateLoading.cpp` all loading loops need to be screened for an invalid input/missing file
- [x] property loading
- [x] entity loading
- [x] state loading

Errors returned must be displayed and written to `log.txt` before exiting the program
- [x] Error reporting
