### ISSUE TITLE
Implement a proper user interface

### ISSUE THREAD

**Issue by weiffert** [weiffert/Missile-Command#4]
The current game does not have a:
- [x] start ui- more streamlined UI at the beginning, UI in place is very basic
- [x] pause ui- pause the game loop and display a splash screen or other message
- [x] game end ui

**Comment by coverp** [comment]
If there's time a high score system would be good to implement as well, but not essential

**Comment by weiffert** [comment]
Note: this should be in a new branch because it is different than the game engine. Plus, the game engine class will be unusable for testing while the new collision checking is being implemented.
